version: 2.1
jobs:
  deployed:
    docker:
      - image: circleci/python:3.7.4
        auth: 
          username: sebasdev321
          password: $DOCKERHUB_PASSWORD

    environment:
      CLOUDNAME: $CLOUDNAME
      DBURL: $DBURL 
      ENCODE: $ENCODE
      KeyCredentialJSON: $KeyCredentialJSON
      KEYVALUECLOUD: $KEYVALUECLOUD
      SECRETKEYCLOUD: $SECRETKEYCLOUD
      URLCredentialKey: $URLCredentialKey
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install firebase_admin
            pip install -r requirements.txt
            
workflows:
  deployed-workflow:
    jobs:
      - deployed
