version: 2.1
jobs:
  deployed:
    docker:
      - image: circleci/python:3.7.4
        auth: 
          username: sebasdev321
          password: $DOCKERHUB_PASSWORD

    environment:
      CLOUDNAME: fullmarketstorage
      DBURL: https://fullmarket-e6156-default-rtdb.firebaseio.com/
      ENCODE: fullmarket
      KeyCredentialJSON: $2b$10$LXm3XFxHTE2rso2bpHTANuXLZZWoXssChhzfFs0LpW2ZK/Wj4ifmq
      KEYVALUECLOUD: 798549958657717
      SECRETKEYCLOUD: p_BFaQ2XC2C1srYPQ0BkZe5OwKs
      URLCredentialKey: https://api.jsonbin.io/v3/b/624692ab1a1b610f08496185

    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install firebase_admin
            pip install -r requirements.txt
            
workflows:
  deployed-workflow:
    jobs:
      - deployed
